<?xml version="1.0" encoding="utf-8"?><Database Class="LibraryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Novels">
    <Type Name="Novel">
      <Column Name="NovelTitle" Type="System.String" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rank" Type="System.Int32" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" CanBeNull="false" />
      <Column Name="LastReadChapterID" Type="System.Int32" CanBeNull="false" />
      <Column Name="ChaptersNotReadCount" Type="System.Int32" CanBeNull="false" />
      <Column Name="MakeAudio" Type="System.Boolean" CanBeNull="false" />
      <Association Name="Novel_Chapter" Member="Chapters" ThisKey="NovelTitle" OtherKey="NovelTitle" Type="Chapter" />
      <Association Name="Novel_Source" Member="Sources" ThisKey="NovelTitle" OtherKey="NovelTitle" Type="Source" />
    </Type>
  </Table>
  <Table Name="" Member="Chapters">
    <Type Name="Chapter">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NovelTitle" Type="System.String" CanBeNull="false" />
      <Column Name="ChapterTitle" Type="System.String" CanBeNull="false" />
      <Column Name="Index" Type="System.Int32" CanBeNull="false" />
      <Column Name="Read" Type="System.Boolean" CanBeNull="false" />
      <Association Name="Chapter_ChapterUrl" Member="ChapterUrls" ThisKey="ID" OtherKey="ChapterID" Type="ChapterUrl" />
      <Association Name="Novel_Chapter" Member="Novel" ThisKey="NovelTitle" OtherKey="NovelTitle" Type="Novel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="ChapterUrls">
    <Type Name="ChapterUrl">
      <Column Name="Url" Type="System.String" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Valid" Type="System.Boolean" CanBeNull="false" />
      <Column Name="ChapterID" Type="System.Int32" CanBeNull="false" />
      <Column Name="SourceID" Type="System.Int32" CanBeNull="false" />
      <Association Name="Chapter_ChapterUrl" Member="Chapter" ThisKey="ChapterID" OtherKey="ID" Type="Chapter" IsForeignKey="true" />
      <Association Name="Source_ChapterUrl" Member="Source" ThisKey="SourceID" OtherKey="ID" Type="Source" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="Sources">
    <Type Name="Source">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SourceNovelLocation" Type="System.String" CanBeNull="false" />
      <Column Name="SourceNovelID" Type="System.String" CanBeNull="false" />
      <Column Member="NovelTitle" Type="System.String" CanBeNull="false" />
      <Association Name="Source_ChapterUrl" Member="ChapterUrls" ThisKey="ID" OtherKey="SourceID" Type="ChapterUrl" />
      <Association Name="Novel_Source" Member="Novel" ThisKey="NovelTitle" OtherKey="NovelTitle" Type="Novel" IsForeignKey="true" />
    </Type>
  </Table>
</Database>